# Generated by Django 2.0.2 on 2018-03-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180303_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplooyee',
            name='padron',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.Padron'),
        ),
    ]
