# Generated by Django 2.0.2 on 2018-03-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180303_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplooyee',
            name='padron',
        ),
        migrations.RemoveField(
            model_name='emplooyee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Emplooyee',
        ),
    ]
