# Generated by Django 2.0.2 on 2018-03-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180303_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padron',
            name='campus',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
