# Generated by Django 2.0.2 on 2018-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180305_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
