# Generated by Django 2.0.2 on 2018-03-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='fecha_fin',
            new_name='fecha_de_fin',
        ),
        migrations.RenameField(
            model_name='voting',
            old_name='fecha_inicio',
            new_name='fecha_de_inicio',
        ),
    ]
