# Generated by Django 2.0.2 on 2018-03-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180306_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='pregunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voting',
            name='tema',
            field=models.TextField(),
        ),
    ]
