# Generated by Django 2.0.2 on 2018-03-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20180306_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='fecha_de_fin',
            new_name='fecha_de_cierre',
        ),
    ]
