# Generated by Django 2.0.2 on 2018-05-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180311_0924'),
        ('management', '0004_auto_20180306_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='delegacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Delegacion'),
        ),
    ]
