# Generated by Django 2.0.2 on 2018-05-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_voting_delegacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='respuesta',
            field=models.TextField(),
        ),
    ]
